[build]
  base = "examples/using-remark-link-card"
  publish = "public/"
  command = "apt-get update && apt-get install -y \n
    locales \n
    gconf-service \n
    libasound2 \n
    libatk1.0-0 \n
    libc6 \n
    libcairo2 \n
    libcups2 \n
    libdbus-1-3 \n
    libexpat1 \n
    libfontconfig1 \n
    libgcc1 \n
    libgconf-2-4 \n
    libgdk-pixbuf2.0-0 \n
    libglib2.0-0 \n
    libgtk-3-0 \n
    libnspr4 \n
    libpango-1.0-0 \n
    libpangocairo-1.0-0 \n
    libstdc++6 \n
    libx11-6 \n
    libx11-xcb1 \n
    libxcb1 \n
    libxcomposite1 \n
    libxcursor1 \n
    libxdamage1 \n
    libxext6 \n
    libxfixes3 \n
    libxi6 \n
    libxrandr2 \n
    libxrender1 \n
    libxss1 \n
    libxtst6 \n
    ca-certificates \n
    fonts-liberation \n
    libappindicator1 \n
    libnss3 \n
    lsb-release \n
    xdg-utils\n
    && gatsby build
  "
